const WebSocket = require('ws');
const port = 9001;

const wss = new WebSocket.Server({ port: port });

const fs = require('fs');
const path = require('path');
wss.on('connection', function connection(ws) {
	ws.on('message', function incoming(message) {
		const parsed = JSON.parse(message);
		fs.writeFileSync(path.join(require.main.filename, '../../', './page/page.view.tree'), parsed.tree, 'utf-8')
		fs.writeFileSync(path.join(require.main.filename, '../../', './page/page.view.ts'), parsed.ts, 'utf-8')
		fs.writeFileSync(path.join(require.main.filename, '../../', './page/page.view.css'), parsed.css, 'utf-8')
		fs.writeFileSync(require('path').join(require.main.filename, '../../', './page/-/test.html'), getTemplate(new Date().getTime()), 'utf-8', (err) => {
			console.log(err)
		})
		ws.send(message);
	});

});

const getTemplate = (time) => {
	return `
	
	<!-- Disable quirks mode -->
<!DOCTYPE html>
<!-- Allow height:100% in body -->
<html style=" height: 100% ">
	<!-- Force utf-8 encoding -->
	<meta charset="utf-8" />
	<!-- Disable mobile browser auto zoom, $mol is adaptive -->
	<meta
		name="viewport"
		content="width=device-width, height=device-height, initial-scale=1"
	/>
	<!-- link to autogenerated js bundle -->
	<script src="web.js?${time}"></script>
	
	<!-- link to optional autogenerated test js bundle -->
	<!-- <script src="web.test.js?${time}" defer></script> -->
	<!-- autobind component to element on load -->
	<body mol_view_root="$my_repl_page"><script src="web.test.js" charset="utf-8" defer></script></body>
</html>
	
	`
}
